"""empty message

Revision ID: 03f2617ffb04
Revises: b3ead697c44a
Create Date: 2018-10-08 21:16:42.333952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f2617ffb04'
down_revision = 'b3ead697c44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_image_url')
    # ### end Alembic commands ###
